# Building a Neural Network from Scratch!
(Built on the fundamental math behind Machine Learning. NOT just 10 lines of Tensorflow, as much fun as that is.)<br>
Credits: MIT PhD candidate Dr. Raj Dandekar's notes<br><br>
Code written by me, images taken directly from his notes.<br>
<hr>

<h2>Part 1</h2>

<h3> First neuron </h3>
<img src="images/1.1.png">

In [2]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

output = (inputs[0]*weights[0]) + (inputs[1]*weights[1]) + (inputs[2]*weights[2]) + bias

print("Output: " + str(output))
# The ultimate goal is to come up with the RIGHT weights for each calculation (neuron)
# And then, structure them in the right way (network of neurons).

Output: 2.3


<h3>First <u>Layer</u> of Neurons</h3>
<img src="images/1.2.png">

In [3]:
# Set up
inputs = [1, 2, 3]
weights = [[0.2, 0.8, -0.5],
           [0.5, -0.91, 0.26],
           [-0.26, -0.27, 0.17],
           ]
biases = [2, 3, 0.5]

In [4]:
# Hard coded, WITHOUT loops, just to understand the concept
weights1 = weights[0]
weights2 = weights[1]
weights3 = weights[2]

outputs = [
    (inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + biases[0]), # neuron 1
    (inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + biases[1]), # neuron 2
    (inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + biases[2]), # neuron 3
]

print("Outputs: " + str(outputs))

Outputs: [2.3, 2.46, 0.20999999999999996]


In [5]:
# WITH a loop, for actual use (any number of neurons, layers, inputs, etc.)

outputs = []
for neuron_weights, neuron_bias in zip(weights, biases): 
    # zip() allows parallel looping, to access items in different lists, ideally of the same size
    output = neuron_bias
    
    for input, weight in zip(inputs, neuron_weights):
        output += input*weight
    
    outputs.append(output)

print("Outputs: " + str(outputs))

Outputs: [2.3000000000000003, 2.46, 0.20999999999999996]


<hr>
<h2> Part 2 </h2>


<h3>Single neuron <u>with np.dot</u></h3>

In [6]:
import numpy as np

inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

output = np.dot(inputs, weights) + bias
print("Output: " + str(output))

Output: 2.3


<h3>Entire layer <u>with np.dot</u></h3>

Using Matrix-Vector multiplication!

<img src="images/2.1.png" width="600px">

In [7]:
# Set up (same as part 1)
inputs = [1, 2, 3]
weights = [[0.2, 0.8, -0.5],
           [0.5, -0.91, 0.26],
           [-0.26, -0.27, 0.17],
            ]
biases = [2, 3, 0.5]

outputs = np.dot(weights, inputs) + biases # Each row of weights is multiplied by inputs column, exactly how weights are used 
print("Outputs: " + str(outputs))

# ENTIRE code in part 1 with a loop, is replaced by just ONE line!! SO COOL.

Outputs: [2.3  2.46 0.21]


<h3>Complete batch of data <u>with np.dot</u></h3>

With matrix-matrix multiplication

<img src="images/2.2.png" width="500px" height="255.5px" style="margin-right:10px"><img src="images/2.3.png" width="500px">

In [8]:
# each row represents the inputs for one specific neuron
inputs = [[1, 2, 3, 2.5], 
          [2, 5, -1, 2],
          [-1.5, 2.7, 3.3, -0.8]]


# Each row represents the weights for one specific neuron... 
# Later transposed to make sense in sync with how matrix multiplication works - 
# - each row of matrix A multiplied with each COLUMN of matrix B
weights = [[0.2, 0.8, -0.5, 1], 
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights = np.array(weights) # np.dot doesnt take lists, so must convert to array

outputs = np.dot(inputs, weights.T) + biases # The bias just adds the number to every item in that column.

print("Outputs: \n" + str(outputs))


Outputs: 
[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


<hr>
<h2>Part 3</h2>


<h3> Input Layer + 2 hidden layers of neurons </h3>
<img src="images/3.1.png" width="300px">

In [39]:

## Input Layer
inputs = [[1, 2, 3, 2.5], #3x4 matrix
          [2, 5, -1, 2],
          [-1.5, 2.7, 3.3, -0.8]]


## HIDDEN LAYER 1 => 3 neurons, with 4 weights (equal to number of inputs) and 1 bias each. 
weights1 = [[0.2, 0.8, -0.5, 1],  #3x4 matrix
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases1 = [2, 3, 0.5]

## HIDDEN LAYER 2 => 3 neurons, with 3 weights (now its 3 because inputs are only 3, taken from previous hidden layer) and 1 bias each.
weights2 = [[0.1, -0.14, 0.5], #3x3 matrix
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]
##########################################################

weights1 = np.array(weights1)
weights2 = np.array(weights2)

layer1output = np.dot(inputs, weights1.T) + biases1 # dot product of 3x4 and 4x3 matrices = 3x3 matrix

# layer1output is then passed as INPUT to the 2nd hidden layer, which then gives ITS output.
layer2output = np.dot(layer1output, weights2.T) + biases2 # dot product of 3x3 and 3x3 matrices = 3x3 matrix

print("Outputs:\n" + str(layer2output)) # Each row is the output for one batch of data...

Outputs:
[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


<h3>Adding final (output) layer</h3>

In [42]:
# Creating final layer with just 1 neuron, so we get a single number as output for each batch of data

weights3 = [[0.2, 0.3, 0.4]]
bias = [0.5]

weights3 = np.array(weights3)

layer3output = np.dot(layer2output, weights3.T) + bias

<h3>Input layer (4 input neurons) -> Hidden layer 1 (3 neurons) -> Hidden layer 2 (3 neurons) -> Output layer (1 output neuron)</h3>

In [43]:
print("Single value output for each input batch:\n" + str(layer3output))

Single value output for each input batch:
[[-0.527435]
 [-2.5766  ]
 [ 0.582514]]


<hr>
<h2>Part 4</h2>